# .pre-commit-config.yaml
default_language_version:
  python: python3.10
default_stages: [commit, push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks  # general checks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1024']
        exclude: "([a-zA-Z0-9_]{1,}\\.ipynb|.+?\\.png)"
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-json
        exclude : ^.vscode/
      - id: pretty-format-json
        args: ['--autofix']
        exclude : ^.vscode/
      - id: debug-statements
      - id: detect-private-key
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, master]
  - repo: https://github.com/MarcoGorelli/madforhooks  # additional hooks
    rev: 0.4.1
    hooks:
      - id: no-print-statements
        files: ^src/
  - repo: https://github.com/psf/black  # black formatter
    rev: 23.7.0
    hooks:
      - id: black
        files: ^src/
  - repo: https://github.com/PyCQA/isort  # isort sort imports
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^src/
  - repo: https://github.com/pycqa/flake8  # flake8 linter
    rev: 6.1.0
    hooks:
      - id: flake8
        files: ^src/
  - repo: https://github.com/nbQA-dev/nbQA  # generalised notebook QA
    rev: 1.7.0
    hooks:
      # - id: nbqa-black  # not yet
      - id: nbqa-isort
        additional_dependencies: [isort==5.10.1]
